services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: "/auth"
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    command:
      - start-dev